# Generated by Django 5.2.8 on 2025-11-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cancelledorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
