# Generated by Django 5.2.8 on 2025-11-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_stock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='outstanding_containers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
