# Generated by Django 5.2.8 on 2025-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_barangay_municipality_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liters',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
