# Generated by Django 5.2.8 on 2025-11-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_delivery_eta_minutes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
