# Generated by Django 4.2.7 on 2024-05-20 10:30

from django.db import migrations


def clear_profile_addresses(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.update(address='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_profile_address'),
    ]

    operations = [
        migrations.RunPython(clear_profile_addresses, reverse_code=migrations.RunPython.noop),
    ]