# Generated by Django 5.2.8 on 2025-11-28 10:05

from django.db import migrations, models
import django.db.models.deletion


def convert_address_field(apps, schema_editor):
    # Clear all address data since we can't convert text to ForeignKey
    Profile = apps.get_model('core', 'Profile')
    Profile.objects.update(address=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clear_profile_addresses'),
    ]

    operations = [
        # First clear all address data
        migrations.RunPython(convert_address_field, reverse_code=migrations.RunPython.noop),
        # Then remove the old TextField address field
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        # Finally add the proper ForeignKey field
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
    ]