# Generated by Django 5.2.8 on 2025-11-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_convert_profile_address_to_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='street_house_number',
        ),
    ]
