# Generated by Django 5.2.8 on 2025-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_barangay_street_house_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='barangay',
        ),
        migrations.AddField(
            model_name='route',
            name='barangays',
            field=models.ManyToManyField(to='core.barangay'),
        ),
    ]
