# Generated by Django 5.2.8 on 2025-11-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
