# Generated by Django 5.2.8 on 2025-11-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_deployment_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('barangay', 'full_address')},
        ),
    ]
