# Generated by Django 5.2.8 on 2025-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_address_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='municipality',
        ),
        migrations.AddField(
            model_name='route',
            name='municipalities',
            field=models.ManyToManyField(to='core.municipality'),
        ),
    ]
