# Generated by Django 5.2.8 on 2025-11-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_route_municipality_route_municipalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
