# Generated by Django 5.2.8 on 2025-11-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_deployment_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
