# Generated by Django 5.2.8 on 2025-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_address_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]