# Generated by Django 5.2.8 on 2025-11-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_deployment_deployment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deployment_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
