# Generated by Django 5.2.8 on 2025-11-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_deployment_deployment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
