# Generated by Django 5.2.8 on 2025-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_order_free_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
