# Generated by Django 5.2.8 on 2025-11-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delivery_delivered_quantity'),
    ]

    operations = [
    ]
