# Generated by Django 5.2.8 on 2025-12-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20251130_1752'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barangay',
            unique_together={('municipality', 'name')},
        ),
    ]
