# Generated by Django 5.2.8 on 2025-12-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_profile_middle_name_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
