# Generated by Django 5.2.8 on 2025-12-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
