# Generated by Django 5.2.8 on 2025-12-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_deployment_returned_at_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='returned_containers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]