# Generated by Django 5.2.8 on 2025-12-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_deployment_returned_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='initial_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
