# Generated by Django 5.2.8 on 2025-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_deployment_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='returned_containers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
