# Generated by Django 5.2.8 on 2025-12-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delivery_returned_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinorder',
            name='free_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
