# Generated by Django 5.2.8 on 2025-12-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_walkinorder_free_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinorder',
            name='returned_containers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
